import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.findLab': 'Trouver Vétérinaire',
    'nav.findClient': 'Trouver un Client',
    'nav.results': 'Mes Résultats',
    'nav.login': 'Se Connecter',
    'nav.PADRequests': 'Demandes CVD',
    'nav.logout': 'Se Déconnecter',

    // Hero Section
    'hero.title': 'Soins Vétérinaires pour Vos Animaux',
    'hero.subtitle': 'Trouvez le vétérinaire le plus proche de chez vous pour prendre soin de vos chiens, chats et autres animaux de compagnie.',
    'hero.findLab': 'Trouver un Vétérinaire',
    'hero.login': 'Se Connecter',

    // Features
    'features.title': 'Pourquoi Choisir VetDz ?',
    'features.subtitle': 'Découvrez les avantages de notre réseau de vétérinaires et profitez d\'un service de qualité pour vos animaux.',
    'features.analyses.title': 'Soins Complets',
    'features.analyses.desc': 'Consultations, vaccinations, chirurgies et soins d\'urgence avec des équipements modernes.',
    'features.results.title': 'Suivi Personnalisé',
    'features.results.desc': 'Accès en ligne aux informations de santé de votre animal, 24h/7j.',
    'features.home.title': 'Visite à Domicile',
    'features.home.desc': 'Service de consultation à domicile pour le confort de votre animal.',
    'features.security.title': 'Sécurité et Confidentialité',
    'features.security.desc': 'Protection complète des données médicales de vos animaux avec chiffrement sécurisé.',
    'features.team.title': 'Vétérinaires Qualifiés',
    'features.team.desc': 'Vétérinaires diplômés et expérimentés pour des soins de haute qualité.',
    'features.tracking.title': 'Historique Médical',
    'features.tracking.desc': 'Historique complet des soins et vaccinations de vos animaux.',

    // Find vet
    'findLab.title': 'Trouvez un Vétérinaire Près de Chez Vous',
    'findLab.subtitle': 'Localisez rapidement les cliniques vétérinaires dans votre région et prenez rendez-vous en quelques clics.',
    'findLab.seoTitle': 'Trouver un Vétérinaire - Soins Vétérinaires',
    'findLab.seoDescription': 'Trouvez la clinique vétérinaire la plus proche de chez vous. Localisation, horaires et services disponibles.',
    'findLab.keyword1': 'trouver vétérinaire',
    'findLab.keyword2': 'vétérinaire proche',
    'findLab.keyword3': 'soins animaux',
    'findLab.keyword4': 'localisation vétérinaire',
    'findLab.placeholder': 'Entrez votre adresse ou code postal',
    'findLab.myLocation': 'Ma position',
    'findLab.search': 'Rechercher',
    'findLab.call': 'Appeler',
    'findLab.homeCollection': 'Collecte à domicile',
    'findLab.services': 'Services:',
    'findLab.notFound': 'Vous ne trouvez pas de vétérinaire dans votre région ?',
    'findLab.contact': 'Contactez-nous pour plus d\'informations',
    'findLab.goLocation': 'Aller au lieu',
    'findLab.searching': 'Recherche en cours...',
    'findLab.loading': 'Chargement des vétérinaires...',
    'findLab.found': 'Vétérinaires trouvés ({count})',
    'findLab.defaultName': 'Vétérinaire',
    'findLab.phoneNotAvailable': 'Téléphone non disponible',
    'findLab.mapCentered': 'Carte recentrée',
    'findLab.mapCenteredDesc': 'Carte centrée sur {labName}',
    'findLab.noResults': 'Aucun vétérinaire trouvé dans cette zone.',

    // Map page strings
    'map.locationRequired': 'Localisation requise',
    'map.needLocation': 'Nous avons besoin de votre position pour afficher les vétérinaires proches',
    'map.nearbyLabs': 'Vétérinaires Proches',
    'map.scrollHint': 'Faites défiler pour voir tous les vétérinaires',
    'map.openDays': 'Jours ouverts',
    'map.requestPAD': 'Demander consultation à domicile (CVD)',
    'map.locating': 'Localisation...',
    'map.refreshPosition': 'Actualiser Position',
    'map.goToMyPlace': 'Ma position',
    'map.positionUnknown': 'Position inconnue',
    'map.enableLocation': 'Activez votre localisation d\'abord.',
    'map.alreadySent': 'Déjà envoyé',
    'map.alreadySentDesc': 'Vous avez déjà envoyé une demande. Veuillez attendre la réponse.',
    'map.accuracyApproximate': 'Position approximative',
    'map.accuracyVeryPrecise': 'Position très précise',
    'map.accuracyPrecise': 'Position précise',
    'map.accuracyGood': 'Position bonne',
    'map.accuracyIP': 'Position basée sur IP',
    'map.interactiveMap': 'Carte Interactive',
    'map.yourPosition': 'Votre Position',
    'map.accuracy': 'Précision: ±{meters}m',
    'map.loadingLabs': 'Chargement des vétérinaires...',
    'map.noLabsInDB': 'Aucun vétérinaire dans la base de données',
    'map.noLabsAvailable': 'Aucun vétérinaire vérifié n\'est disponible pour le moment',
    'map.call': 'Appeler',
    'map.directions': 'Itinéraire',
    'map.goToLocation': 'Aller à',
    'map.laboratories': 'vétérinaires',

    // CVD strings (Consultation Vétérinaire à Domicile)
    'CVD.loginRequired': 'Vous devez être connecté pour demander une consultation à domicile.',
    'CVD.sendError': 'Demande en cours. Patientez ou attendez la réponse du vétérinaire.',
    'CVD.sendSuccess': 'Demande envoyée',
    'CVD.sendSuccessDesc': 'Demande de consultation à domicile envoyée à {labName}',
    'CVD.defaultMessage': 'Demande de consultation vétérinaire à domicile pour mon animal',
    'CVD.requestMessage': 'Demande de consultation vétérinaire à domicile pour mon animal',
    'CVD.newRequest.title': 'Nouvelle demande CVD',
    'CVD.newRequest.message': 'a demandé une consultation à domicile.',
    'CVD.sentTitle': 'Demande CVD envoyée',
    'CVD.sentDesc': 'Demande de consultation envoyée à',
    'CVD.acceptedTitle': 'CVD acceptée',
    'CVD.acceptedMessage': 'Le vétérinaire a accepté votre demande de consultation à domicile. Restez joignable, ils peuvent vous appeler.',

    // Common
    'common.error': 'Erreur',
    'common.aClient': 'Un client',
    'common.refresh': 'Actualiser',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'Trouvez votre vétérinaire',
    'hero.auth.labTitle': 'Gérez vos consultations',
    'hero.auth.clientSubtitle': 'Découvrez les vétérinaires proches et prenez rendez-vous facilement.',
    'hero.auth.labSubtitle': 'Accédez à vos demandes de consultation et gérez vos dossiers.',

    // Authentication
    'auth.login': 'Se Connecter',
    'auth.signup': 'S\'Inscrire',
    'auth.loginTitle': 'Connexion',
    'auth.signupTitle': 'Créer un Compte',
    'auth.loginSubtitle': 'Accédez à votre espace personnel',
    'auth.signupSubtitle': 'Rejoignez notre plateforme vétérinaire',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.client': 'Client',
    'auth.vet': 'Vétérinaire',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.birthDate': 'Date de naissance',
    'auth.labName': 'Nom de la clinique',
    'auth.vetName': 'Nom de la vet',
    'auth.professionalEmail': 'Email professionnel',
    'auth.siret': 'Numéro SIRET',
    'auth.address': 'Adresse',
    'auth.terms': 'J\'accepte les conditions d\'utilisation',
    'auth.professionalTerms': 'J\'accepte les conditions professionnelles',
    'auth.createAccount': 'Créer un compte',

    // Services
    'services.bloodTests': 'Consultations',
    'services.bloodTests.desc': 'Examens et consultations vétérinaires',
    'services.urineTests': 'Vaccinations',
    'services.urineTests.desc': 'Vaccins et rappels pour vos animaux',
    'services.homeCollection': 'Visite à Domicile',
    'services.homeCollection.desc': 'Consultation vétérinaire à votre domicile',
    'services.rapidResults': 'Urgences',
    'services.rapidResults.desc': 'Soins d\'urgence pour vos animaux',

    // Results
    'results.title': 'Mes Résultats',
    'results.download': 'Télécharger',
    'results.status.completed': 'Terminé',
    'results.status.pending': 'En attente',
    'results.status.reviewed': 'Examiné',
    'results.labHistory': 'Historique des résultats envoyés aux clients',
    'results.clientHistory': 'Historique de vos résultats de tests médicaux',
    'results.searchPlaceholder': 'Rechercher par titre, description ou nom...',
    'results.results': 'Résultats',
    'results.loading': 'Chargement...',
    'results.found': 'résultat(s) trouvé(s)',
    'results.loadingResults': 'Chargement des résultats',
    'results.loadError': 'Impossible de charger les résultats.',
    'results.downloadStarted': 'Téléchargement commencé',
    'results.downloading': 'Téléchargement',
    'results.downloadErrorTitle': 'Erreur de téléchargement',
    'results.downloadErrorDesc': 'Impossible de télécharger le fichier.',
    'results.newAvailableTitle': 'Nouveau résultat disponible',
    'results.newAvailableMessage': 'Le vétérinaire a envoyé un résultat: "{filename}".',

    // vet dashboard
    'lab.header': 'Tableau de Bord - Vétérinaire',
    'lab.headerSubtitle': 'Gérez vos demandes, résultats et paramètres vétérinaires',
    'lab.findClient': 'Trouver un Client',
    'lab.PADRequests': 'Demandes CVD',
    'lab.searchClients': 'Rechercher des Clients',
    'lab.searchClientsDesc': 'Trouvez des clients nécessitant des consultations à domicile',
    'lab.searchPlaceholder': 'Rechercher par nom, email ou téléphone...',
    'lab.sendResult': 'Envoyer Résultat',
    'lab.noClientFor': 'Aucun client trouvé',
    'lab.noClientsYet': 'Aucun client inscrit pour le moment',
    'lab.noClientsHint': 'Les clients apparaîtront ici une fois qu\'ils se seront inscrits sur la plateforme',
    'lab.receivedPAD': 'Demandes CVD Reçues',
    'lab.receivedPADDesc': 'Gérez les demandes de consultation à domicile',
    'lab.status.pending': 'En attente',
    'lab.status.accepted': 'Acceptée',
    'lab.status.rejected': 'Refusée',
    'lab.viewExactLocation': 'Voir Localisation Exacte',
    'lab.accept': 'Accepter',
    'lab.reject': 'Refuser',

    // vet Home Page
    'labHome.seoTitle': 'Espace Vétérinaire - VetDz',
    'labHome.seoDescription': 'Plateforme complète pour les cliniques vétérinaires. Connectez-vous avec les propriétaires d\'animaux, gérez les consultations et optimisez votre flux de travail.',
    'labHome.keyword1': 'vétérinaire',
    'labHome.keyword2': 'soins animaux',
    'labHome.keyword3': 'consultation',
    'labHome.keyword4': 'animaux',
    'labHome.title': 'Espace Vétérinaire',
    'labHome.heroDescription': 'Plateforme complète pour les cliniques vétérinaires. Connectez-vous avec les propriétaires d\'animaux, gérez les consultations et optimisez votre flux de travail.',
    'labHome.ctaFindClients': 'Trouver des Clients',
    'labHome.ctaManageRequests': 'Gérer les Demandes',
    'labHome.features.title': 'Fonctionnalités Vétérinaire',
    'labHome.features.subtitle': 'Tout ce dont vous avez besoin pour gérer efficacement votre clinique',
    'labHome.features.findClients.title': 'Trouver des Clients',
    'labHome.features.findClients.desc': 'Recherchez et connectez-vous avec des propriétaires d\'animaux qui ont besoin de vos services vétérinaires.',
    'labHome.features.findClients.button': 'Rechercher des Clients',
    'labHome.features.managePAD.title': 'Gérer les Consultations à Domicile',
    'labHome.features.managePAD.desc': 'Recevez et gérez les demandes de consultation vétérinaire à domicile (CVD).',
    'labHome.features.managePAD.button': 'Voir les Demandes CVD',
    'labHome.features.sendResults.title': 'Partager les Documents',
    'labHome.features.sendResults.desc': 'Partagez facilement les documents vétérinaires avec vos clients au format PDF.',
    'labHome.features.sendResults.button': 'Gérer les Documents',
    'labHome.stats.clientsActive': 'Clients Actifs',
    'labHome.stats.analysesDone': 'Consultations Terminées',
    'labHome.stats.clientSatisfaction': 'Satisfaction Client',
    'labHome.stats.avgDelay': 'Délai Moyen',
    'labHome.howItWorks.title': 'Comment ça Marche',
    'labHome.howItWorks.subtitle': 'Processus simple en 3 étapes pour vous connecter avec vos clients',
    'labHome.howItWorks.step1.title': 'Rechercher des Clients',
    'labHome.howItWorks.step1.desc': 'Utilisez notre système de recherche pour trouver des propriétaires d\'animaux qui ont besoin de vos services',
    'labHome.howItWorks.step2.title': 'Recevoir des Demandes',
    'labHome.howItWorks.step2.desc': 'Les clients vous envoient des demandes de visite à domicile que vous pouvez accepter ou refuser',
    'labHome.howItWorks.step3.title': 'Partager les Documents',
    'labHome.howItWorks.step3.desc': 'Partagez facilement les documents vétérinaires dans un format PDF sécurisé',
    'labHome.cta.title': 'Prêt à commencer ?',
    'labHome.cta.subtitle': 'Rejoignez notre plateforme et commencez à vous connecter avec des clients dès aujourd\'hui',
    'labHome.cta.button': 'Aller au Tableau de Bord',

    // Footer
    'footer.subtitle': 'Cliniques Vétérinaires en Algérie',
    'footer.description': 'Réseau de cliniques vétérinaires offrant des services de qualité avec visite à domicile, soins d\'urgence et suivi personnalisé pour vos animaux.',
    'footer.services': 'Services',
    'footer.newsletter': 'Newsletter',
    'footer.stayUpdated': 'Restez informé de nos nouveaux services et conseils santé.',
    'footer.emailPlaceholder': 'Votre email',
    'footer.subscribing': 'Inscription...',
    'footer.subscribe': 'S\'abonner',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',

    // Notifications
    'notifications.loading': 'Chargement des notifications...',
    'notifications.empty': 'Aucune notification',
    'notifications.view': 'Voir',
    'notifications.viewAll': 'Voir toutes les notifications',
    'notifications.title': 'Notifications',
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.findLab': 'Find Veterinarian',
    'nav.findClient': 'Find Client',
    'nav.results': 'My Results',
    'nav.login': 'Login',
    'nav.PADRequests': 'Home Visits',
    'nav.logout': 'Logout',

    // Hero Section
    'hero.title': 'Veterinary Care for Your Pets',
    'hero.subtitle': 'Find the nearest veterinarian to take care of your dogs, cats and other pets.',
    'hero.findLab': 'Find Veterinarian',
    'hero.login': 'Login',

    // Features
    'features.title': 'Why Choose VetDz?',
    'features.subtitle': 'Discover the advantages of our veterinary network and enjoy quality service for your pets.',
    'features.analyses.title': 'Complete Care',
    'features.analyses.desc': 'Consultations, vaccinations, surgeries and emergency care with modern equipment.',
    'features.results.title': 'Online Tracking',
    'features.results.desc': 'Online access to your pet\'s medical records, 24/7.',
    'features.home.title': 'Home Visits',
    'features.home.desc': 'Home consultation service for your pet\'s comfort.',
    'features.security.title': 'Security & Privacy',
    'features.security.desc': 'Complete protection of your pet\'s medical data with secure encryption.',
    'features.team.title': 'Qualified Veterinarians',
    'features.team.desc': 'Licensed and experienced veterinarians for high-quality care.',
    'features.tracking.title': 'Medical History',
    'features.tracking.desc': 'Complete history of your pet\'s care and vaccinations.',

    // Find vet
    'findLab.title': 'Find a Veterinarian Near You',
    'findLab.subtitle': 'Quickly locate veterinary clinics in your area and book appointments in just a few clicks.',
    'findLab.seoTitle': 'Find a Veterinarian - Veterinary Care',
    'findLab.seoDescription': 'Find the nearest veterinary clinic to you. Location, opening hours and available services.',
    'findLab.keyword1': 'find veterinarian',
    'findLab.keyword2': 'nearby vet',
    'findLab.keyword3': 'pet care',
    'findLab.keyword4': 'vet location',
    'findLab.placeholder': 'Enter your address or postal code',
    'findLab.myLocation': 'My location',
    'findLab.search': 'Search',
    'findLab.call': 'Call',
    'findLab.homeCollection': 'Home collection',
    'findLab.services': 'Services:',
    'findLab.notFound': "Can't find a veterinarian in your area?",
    'findLab.contact': 'Contact us for more information',
    'findLab.goLocation': 'Go location',
    'findLab.searching': 'Searching...',
    'findLab.loading': 'Loading laboratories...',
    'findLab.found': 'Laboratories found ({count})',
    'findLab.defaultName': 'vet',
    'findLab.phoneNotAvailable': 'Phone not available',
    'findLab.mapCentered': 'Map centered',
    'findLab.mapCenteredDesc': 'Map centered on {labName}',
    'findLab.noResults': 'No vet found in this area.',

    // Map page strings
    'map.locationRequired': 'Location required',
    'map.needLocation': 'We need your position to show nearby veterinarians',
    'map.nearbyLabs': 'Nearby Veterinarians',
    'map.scrollHint': 'Scroll to view all veterinarians',
    'map.openDays': 'Open days',
    'map.requestPAD': 'Request home consultation',
    'map.locating': 'Locating...',
    'map.refreshPosition': 'Refresh Position',
    'map.goToMyPlace': 'My location',
    'map.positionUnknown': 'Unknown position',
    'map.enableLocation': 'Enable your location first.',
    'map.alreadySent': 'Already sent',
    'map.alreadySentDesc': 'You have already sent a request. Please wait for the response.',
    'map.accuracyApproximate': 'Approximate position',
    'map.accuracyVeryPrecise': 'Very precise position',
    'map.accuracyPrecise': 'Precise position',
    'map.accuracyGood': 'Good position',
    'map.accuracyIP': 'IP-based position',
    'map.interactiveMap': 'Interactive Map',
    'map.yourPosition': 'Your Position',
    'map.accuracy': 'Accuracy: ±{meters}m',
    'map.loadingLabs': 'Loading laboratories...',
    'map.noLabsInDB': 'No vet in database',
    'map.noLabsAvailable': 'No verified vet is available at the moment',
    'map.call': 'Call',
    'map.directions': 'Directions',
    'map.goToLocation': 'Go to location',
    'map.laboratories': 'laboratories',

    // CVD strings (Home Veterinary Consultation)
    'CVD.loginRequired': 'You must be logged in to request a home consultation.',
    'CVD.sendError': 'Request in progress. Please wait for the vet response.',
    'CVD.sendSuccess': 'Request sent',
    'CVD.sendSuccessDesc': 'Home consultation request sent to {labName}',
    'CVD.defaultMessage': 'Home veterinary consultation request for my pet',
    'CVD.requestMessage': 'Home veterinary consultation request for my pet',
    'CVD.newRequest.title': 'New CVD request',
    'CVD.newRequest.message': 'has requested a home consultation.',
    'CVD.sentTitle': 'CVD request sent',
    'CVD.sentDesc': 'Home consultation request sent to',
    'CVD.acceptedTitle': 'CVD accepted',
    'CVD.acceptedMessage': 'The vet has accepted your request. Stay reachable, they may call you.',

    // Common
    'common.error': 'Error',
    'common.aClient': 'A client',
    'common.refresh': 'Refresh',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'Find your veterinarian',
    'hero.auth.labTitle': 'Manage your consultations',
    'hero.auth.clientSubtitle': 'Discover nearby veterinarians and book appointments easily.',
    'hero.auth.labSubtitle': 'Access your consultation requests and manage your records.',

    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.loginTitle': 'Login',
    'auth.signupTitle': 'Create Account',
    'auth.loginSubtitle': 'Access your personal space',
    'auth.signupSubtitle': 'Join our vet platform',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.client': 'Client',
    'auth.vet': 'Veterinarian',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.birthDate': 'Date of Birth',
    'auth.labName': 'vet Name',
    'auth.vetName': 'Clinic Name',
    'auth.professionalEmail': 'Professional Email',
    'auth.siret': 'SIRET Number',
    'auth.address': 'Address',
    'auth.terms': 'I accept the terms of use',
    'auth.professionalTerms': 'I accept the professional terms',
    'auth.createAccount': 'Create account',

    // Services
    'services.bloodTests': 'Consultations',
    'services.bloodTests.desc': 'Veterinary exams and consultations',
    'services.urineTests': 'Vaccinations',
    'services.urineTests.desc': 'Vaccines and boosters for your pets',
    'services.homeCollection': 'Home Visits',
    'services.homeCollection.desc': 'Veterinary consultation at your home',
    'services.rapidResults': 'Rapid Results',
    'services.rapidResults.desc': 'Online access to your results',

    // Results
    'results.title': 'My Results',
    'results.download': 'Download',
    'results.status.completed': 'Completed',
    'results.status.pending': 'Pending',
    'results.status.reviewed': 'Reviewed',
    'results.labHistory': 'History of results sent to clients',
    'results.clientHistory': 'History of your medical test results',
    'results.searchPlaceholder': 'Search by title, description or name...',
    'results.results': 'Results',
    'results.loading': 'Loading...',
    'results.found': 'result(s) found',
    'results.loadingResults': 'Loading results',
    'results.loadError': 'Unable to load results.',
    'results.downloadStarted': 'Download started',
    'results.downloading': 'Downloading',
    'results.downloadErrorTitle': 'Download error',
    'results.downloadErrorDesc': 'Unable to download the file.',
    'results.newAvailableTitle': 'New result available',
    'results.newAvailableMessage': 'The vet has sent a result: "{filename}".',

    // vet dashboard
    'lab.header': 'vet Dashboard',
    'lab.headerSubtitle': 'Manage your requests, results and vet settings',
    'lab.findClient': 'Find Client',
    'lab.PADRequests': 'PAD Requests',
    'lab.searchClients': 'Search Clients',
    'lab.searchClientsDesc': 'Find clients and send them PAD requests',
    'lab.searchPlaceholder': 'Search by name, email or phone...',
    'lab.sendResult': 'Send Result',
    'lab.noClientFor': 'No client found',
    'lab.noClientsYet': 'No clients registered yet',
    'lab.noClientsHint': 'Clients will appear here once they register on the platform',
    'lab.receivedPAD': 'Received PAD Requests',
    'lab.receivedPADDesc': 'Manage PAD requests sent by clients',
    'lab.status.pending': 'Pending',
    'lab.status.accepted': 'Accepted',
    'lab.status.rejected': 'Rejected',
    'lab.viewExactLocation': 'View Exact Location',
    'lab.accept': 'Accept',
    'lab.reject': 'Reject',

    // vet Home Page
    'labHome.seoTitle': 'Veterinarian Space - VetDz',
    'labHome.seoDescription': 'Complete platform for veterinary clinics. Connect with pet owners, manage consultations, and optimize your workflow.',
    'labHome.keyword1': 'veterinarian',
    'labHome.keyword2': 'pet care',
    'labHome.keyword3': 'consultation',
    'labHome.keyword4': 'animals',
    'labHome.title': 'Veterinarian Space',
    'labHome.heroDescription': 'Complete platform for veterinary clinics. Connect with pet owners, manage consultations, and optimize your workflow.',
    'labHome.ctaFindClients': 'Find Clients',
    'labHome.ctaManageRequests': 'Manage Requests',
    'labHome.features.title': 'Veterinarian Features',
    'labHome.features.subtitle': 'Everything you need to efficiently manage your clinic',
    'labHome.features.findClients.title': 'Find Clients',
    'labHome.features.findClients.desc': 'Search and connect with clients who need your vet services.',
    'labHome.features.findClients.button': 'Search Clients',
    'labHome.features.managePAD.title': 'Manage PAD Requests',
    'labHome.features.managePAD.desc': 'Receive and manage collection and analysis requests from your clients.',
    'labHome.features.managePAD.button': 'View Requests',
    'labHome.features.sendResults.title': 'Send Results',
    'labHome.features.sendResults.desc': 'Easily send analysis results to your clients in PDF format.',
    'labHome.features.sendResults.button': 'Manage Results',
    'labHome.stats.clientsActive': 'Active Clients',
    'labHome.stats.analysesDone': 'Analyses Completed',
    'labHome.stats.clientSatisfaction': 'Client Satisfaction',
    'labHome.stats.avgDelay': 'Average Delay',
    'labHome.howItWorks.title': 'How it Works',
    'labHome.howItWorks.subtitle': 'Simple 3-step process to connect with your clients',
    'labHome.howItWorks.step1.title': 'Search Clients',
    'labHome.howItWorks.step1.desc': 'Use our search system to find clients who need your services',
    'labHome.howItWorks.step2.title': 'Receive Requests',
    'labHome.howItWorks.step2.desc': 'Clients send you PAD requests that you can accept or refuse',
    'labHome.howItWorks.step3.title': 'Send Results',
    'labHome.howItWorks.step3.desc': 'Easily send analysis results in a secure PDF format',
    'labHome.cta.title': 'Ready to start?',
    'labHome.cta.subtitle': 'Join our platform and start connecting with clients today',
    'labHome.cta.button': 'Go to Dashboard',

    // Footer
    'footer.subtitle': 'Medical Analysis Laboratories',
    'footer.description': 'Network of medical analysis laboratories offering quality services with home collection, fast results and personalized follow-up.',
    'footer.services': 'Services',
    'footer.newsletter': 'Newsletter',
    'footer.stayUpdated': 'Stay informed about our new services and health tips.',
    'footer.emailPlaceholder': 'Your email',
    'footer.subscribing': 'Subscribing...',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',

    // Notifications
    'notifications.loading': 'Loading notifications...',
    'notifications.empty': 'No notifications',
    'notifications.view': 'View',
    'notifications.viewAll': 'View all notifications',
    'notifications.title': 'Notifications',
  },

  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'حول',
    'nav.services': 'الخدمات',
    'nav.findLab': 'العثور على مختبر',
    'nav.findClient': 'البحث عن عميل',
    'nav.results': 'نتائجي',
    'nav.login': 'تسجيل الدخول',
    'nav.PADRequests': 'طلبات PAD',
    'nav.logout': 'تسجيل الخروج',

    // Hero Section
    'hero.title': 'رعاية بيطرية لحيواناتك الأليفة',
    'hero.subtitle': 'ابحث عن أقرب طبيب بيطري للعناية بكلابك وقططك وحيواناتك الأليفة الأخرى.',
    'hero.findLab': 'ابحث عن طبيب بيطري',
    'hero.login': 'تسجيل الدخول',

    // Features
    'features.title': 'لماذا تختار منصتنا؟',
    'features.subtitle': 'اكتشف مزايا شبكة المختبرات الطبية لدينا واستمتع بخدمة عالية الجودة مصممة لتلبية احتياجاتك.',
    'features.analyses.title': 'تحليل شامل',
    'features.analyses.desc': 'تحاليل الدم والبول والكيمياء الحيوية بأحدث المعدات ونتائج موثوقة.',
    'features.results.title': 'نتائج سريعة',
    'features.results.desc': 'الوصول عبر الإنترنت إلى نتائج التحاليل في أسرع وقت ممكن، على مدار الساعة.',
    'features.home.title': 'جمع منزلي',
    'features.home.desc': 'خدمة الجمع المنزلي لراحتك وأمانك.',
    'features.security.title': 'الأمان والخصوصية',
    'features.security.desc': 'حماية كاملة لبياناتك الطبية مع التشفير والامتثال لقانون حماية البيانات.',
    'features.team.title': 'فريق محترف',
    'features.team.desc': 'علماء أحياء وفنيون مؤهلون لتحليل عالي الجودة.',
    'features.tracking.title': 'متابعة شخصية',
    'features.tracking.desc': 'تاريخ كامل لتحاليلك ونصائح شخصية من خبرائنا.',

    // Find vet
    'findLab.title': 'اعثر على مختبر بالقرب منك',
    'findLab.subtitle': 'حدد موقع المختبرات الطبية في منطقتك بسرعة واحجز المواعيد بنقرات قليلة.',
    'findLab.seoTitle': 'ابحث عن مختبر - تحاليل طبية',
    'findLab.seoDescription': 'اعثر على أقرب مختبر طبي إليك. الموقع، أوقات العمل والخدمات المتاحة.',
    'findLab.keyword1': 'ابحث عن مختبر',
    'findLab.keyword2': 'مختبر قريب',
    'findLab.keyword3': 'تحاليل طبية',
    'findLab.keyword4': 'موقع المختبر',
    'findLab.placeholder': 'أدخل عنوانك أو الرمز البريدي',
    'findLab.myLocation': 'موقعي',
    'findLab.search': 'بحث',
    'findLab.call': 'اتصال',
    'findLab.homeCollection': 'جمع منزلي',
    'findLab.services': 'الخدمات:',
    'findLab.notFound': 'لا يمكنك العثور على مختبر في منطقتك؟',
    'findLab.contact': 'اتصل بنا للحصول على مزيد من المعلومات',
    'findLab.goLocation': 'اذهب إلى الموقع',
    'findLab.searching': 'جاري البحث...',
    'findLab.loading': 'تحميل المختبرات...',
    'findLab.found': 'المختبرات الموجودة ({count})',
    'findLab.defaultName': 'مختبر',
    'findLab.phoneNotAvailable': 'الهاتف غير متوفر',
    'findLab.mapCentered': 'تم توسيط الخريطة',
    'findLab.mapCenteredDesc': 'تم توسيط الخريطة على {labName}',
    'findLab.noResults': 'لم يتم العثور على مختبر في هذه المنطقة.',

    // Map page strings
    'map.locationRequired': 'مطلوب تحديد الموقع',
    'map.needLocation': 'نحتاج إلى موقعك لعرض الأطباء البيطريين القريبين',
    'map.nearbyLabs': 'أطباء بيطريون قريبون',
    'map.scrollHint': 'مرر لعرض جميع الأطباء البيطريين',
    'map.openDays': 'أيام العمل',
    'map.requestPAD': 'طلب PAD (الجمع المنزلي)',
    'map.locating': 'جاري تحديد الموقع...',
    'map.refreshPosition': 'تحديث الموقع',
    'map.goToMyPlace': 'موقعي',
    'map.positionUnknown': 'موقع غير معروف',
    'map.enableLocation': 'قم بتفعيل تحديد الموقع أولاً.',
    'map.alreadySent': 'تم الإرسال بالفعل',
    'map.alreadySentDesc': 'لقد أرسلت طلباً بالفعل. يرجى انتظار الرد.',
    'map.accuracyApproximate': 'موقع تقريبي',
    'map.accuracyVeryPrecise': 'موقع دقيق جداً',
    'map.accuracyPrecise': 'موقع دقيق',
    'map.accuracyGood': 'موقع جيد',
    'map.accuracyIP': 'موقع مبني على IP',
    'map.interactiveMap': 'خريطة تفاعلية',
    'map.yourPosition': 'موقعك',
    'map.accuracy': 'الدقة: ±{meters}م',
    'map.loadingLabs': 'تحميل المختبرات...',
    'map.noLabsInDB': 'لا يوجد مختبر في قاعدة البيانات',
    'map.noLabsAvailable': 'لا يوجد مختبر معتمد متاح في الوقت الحالي',
    'map.call': 'اتصال',
    'map.directions': 'الاتجاهات',
    'map.goToLocation': 'الذهاب إلى الموقع',
    'map.laboratories': 'مختبرات',

    // PAD strings
    'PAD.loginRequired': 'يجب أن تكون مسجل الدخول لإرسال طلب PAD.',
    'PAD.sendError': 'طلب PAD قيد المعالجة. يرجى الانتظار أو انتظار رد المختبر.',
    'PAD.sendSuccess': 'تم إرسال الطلب',
    'PAD.sendSuccessDesc': 'تم إرسال طلب PAD إلى {labName}',
    'PAD.defaultMessage': 'طلب PAD مرسل من العميل',
    'PAD.newRequest.title': 'طلب PAD جديد',
    'PAD.newRequest.message': 'أرسل طلب PAD.',
    'PAD.sentTitle': 'تم الإرسال',
    'PAD.sentDesc': 'تم إرسال طلب PAD إلى',
    'PAD.acceptedTitle': 'تم قبول PAD',
    'PAD.acceptedMessage': 'قبل المختبر طلبك. ابق متاحاً، قد يتصلون بك.',

    // Common
    'common.error': 'خطأ',
    'common.aClient': 'عميل',
    'common.refresh': 'تحديث',

    // Hero (authenticated variants)
    'hero.auth.clientTitle': 'اعثر على طبيبك البيطري',
    'hero.auth.labTitle': 'إدارة الاستشارات',
    'hero.auth.clientSubtitle': 'اكتشف الأطباء البيطريين القريبين واحجز المواعيد بسهولة.',
    'hero.auth.labSubtitle': 'الوصول إلى طلبات الاستشارة وإدارة السجلات.',

    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.signupTitle': 'إنشاء حساب',
    'auth.loginSubtitle': 'الوصول إلى مساحتك الشخصية',
    'auth.signupSubtitle': 'انضم إلى منصة المختبرات لدينا',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.client': 'عميل',
    'auth.vet': 'طبيب بيطري',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.phone': 'الهاتف',
    'auth.birthDate': 'تاريخ الميلاد',
    'auth.labName': 'اسم المختبر',
    'auth.vetName': 'اسم العيادة',
    'auth.professionalEmail': 'البريد الإلكتروني المهني',
    'auth.siret': 'رقم SIRET',
    'auth.address': 'العنوان',
    'auth.terms': 'أوافق على شروط الاستخدام',
    'auth.professionalTerms': 'أوافق على الشروط المهنية',
    'auth.createAccount': 'إنشاء حساب',

    // Services
    'services.bloodTests': 'استشارات',
    'services.bloodTests.desc': 'فحوصات واستشارات بيطرية',
    'services.urineTests': 'تطعيمات',
    'services.urineTests.desc': 'لقاحات وجرعات تنشيطية لحيواناتك الأليفة',
    'services.homeCollection': 'زيارات منزلية',
    'services.homeCollection.desc': 'استشارة بيطرية في منزلك',
    'services.rapidResults': 'نتائج سريعة',
    'services.rapidResults.desc': 'الوصول عبر الإنترنت إلى نتائجك',

    // Results
    'results.title': 'نتائجي',
    'results.download': 'تحميل',
    'results.status.completed': 'مكتمل',
    'results.status.pending': 'قيد الانتظار',
    'results.status.reviewed': 'تمت المراجعة',
    'results.labHistory': 'سجل النتائج المرسلة إلى العملاء',
    'results.clientHistory': 'سجل نتائج تحاليلك الطبية',
    'results.searchPlaceholder': 'ابحث حسب العنوان أو الوصف أو الاسم...',
    'results.results': 'النتائج',
    'results.loading': 'جاري التحميل...',
    'results.found': 'نتيجة(نتائج) تم العثور عليها',
    'results.loadingResults': 'جاري تحميل النتائج',
    'results.loadError': 'تعذر تحميل النتائج.',
    'results.downloadStarted': 'بدأ التنزيل',
    'results.downloading': 'جارٍ تنزيل',
    'results.downloadErrorTitle': 'خطأ في التنزيل',
    'results.downloadErrorDesc': 'تعذر تنزيل الملف.',
    'results.newAvailableTitle': 'نتيجة جديدة متاحة',
    'results.newAvailableMessage': 'أرسل المختبر نتيجة: "{filename}".',

    // vet dashboard
    'lab.header': 'لوحة تحكم المختبر',
    'lab.headerSubtitle': 'إدارة الطلبات والنتائج وإعدادات المختبر',
    'lab.findClient': 'البحث عن عميل',
    'lab.PADRequests': 'طلبات PAD',
    'lab.searchClients': 'البحث عن العملاء',
    'lab.searchClientsDesc': 'ابحث عن العملاء وأرسل لهم طلبات PAD',
    'lab.searchPlaceholder': 'ابحث بالاسم أو البريد أو الهاتف...',
    'lab.sendResult': 'إرسال النتيجة',
    'lab.noClientFor': 'لا يوجد عميل',
    'lab.noClientsYet': 'لا يوجد عملاء حتى الآن',
    'lab.noClientsHint': 'سيظهر العملاء هنا بعد التسجيل في المنصة',
    'lab.receivedPAD': 'طلبات PAD المستلمة',
    'lab.receivedPADDesc': 'إدارة طلبات PAD المرسلة من العملاء',
    'lab.status.pending': 'قيد الانتظار',
    'lab.status.accepted': 'مقبولة',
    'lab.status.rejected': 'مرفوضة',
    'lab.viewExactLocation': 'عرض الموقع الدقيق',
    'lab.accept': 'قبول',
    'lab.reject': 'رفض',

    // vet Home Page
    'labHome.seoTitle': 'مساحة المختبر - VetDz',
    'labHome.seoDescription': 'منصة متكاملة لمختبرات التحاليل الطبية. تواصل مع العملاء، وأدر الطلبات، وحسّن سير العمل.',
    'labHome.keyword1': 'مختبر',
    'labHome.keyword2': 'تحاليل طبية',
    'labHome.keyword3': 'PAD',
    'labHome.keyword4': 'نتائج',
    'labHome.title': 'مساحة المختبر',
    'labHome.heroDescription': 'منصة متكاملة لمختبرات التحاليل الطبية. تواصل مع العملاء، وأدر الطلبات، وحسّن سير العمل.',
    'labHome.ctaFindClients': 'البحث عن عملاء',
    'labHome.ctaManageRequests': 'إدارة الطلبات',
    'labHome.features.title': 'ميزات المختبر',
    'labHome.features.subtitle': 'كل ما تحتاجه لإدارة مختبرك بكفاءة',
    'labHome.features.findClients.title': 'البحث عن عملاء',
    'labHome.features.findClients.desc': 'ابحث وتواصل مع العملاء الذين يحتاجون إلى خدمات مختبرك.',
    'labHome.features.findClients.button': 'ابحث عن العملاء',
    'labHome.features.managePAD.title': 'إدارة طلبات PAD',
    'labHome.features.managePAD.desc': 'استقبال وإدارة طلبات السحب والتحاليل من عملائك.',
    'labHome.features.managePAD.button': 'عرض الطلبات',
    'labHome.features.sendResults.title': 'إرسال النتائج',
    'labHome.features.sendResults.desc': 'أرسل نتائج التحاليل بسهولة إلى عملائك بصيغة PDF.',
    'labHome.features.sendResults.button': 'إدارة النتائج',
    'labHome.stats.clientsActive': 'عملاء نشطون',
    'labHome.stats.analysesDone': 'تحاليل منجزة',
    'labHome.stats.clientSatisfaction': 'رضا العملاء',
    'labHome.stats.avgDelay': 'متوسط المدة',
    'labHome.howItWorks.title': 'كيف تعمل المنصة',
    'labHome.howItWorks.subtitle': 'عملية بسيطة من 3 خطوات للتواصل مع عملائك',
    'labHome.howItWorks.step1.title': 'ابحث عن العملاء',
    'labHome.howItWorks.step1.desc': 'استخدم نظام البحث لدينا للعثور على العملاء الذين يحتاجون إلى خدماتك',
    'labHome.howItWorks.step2.title': 'استقبال الطلبات',
    'labHome.howItWorks.step2.desc': 'يرسل العملاء طلبات PAD يمكنك قبولها أو رفضها',
    'labHome.howItWorks.step3.title': 'أرسل النتائج',
    'labHome.howItWorks.step3.desc': 'أرسل نتائج التحاليل بسهولة بصيغة PDF آمنة',
    'labHome.cta.title': 'جاهز للبدء؟',
    'labHome.cta.subtitle': 'انضم إلى منصتنا وابدأ بالتواصل مع العملاء اليوم',
    'labHome.cta.button': 'الانتقال إلى لوحة التحكم',

    // Footer
    'footer.subtitle': 'مختبرات التحاليل الطبية',
    'footer.description': 'شبكة من مختبرات التحاليل الطبية تقدم خدمات عالية الجودة مع جمع منزلي ونتائج سريعة ومتابعة شخصية.',
    'footer.services': 'الخدمات',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.stayUpdated': 'ابقَ على اطلاع على خدماتنا الجديدة ونصائح الصحة.',
    'footer.emailPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribing': 'جارٍ الاشتراك...',
    'footer.subscribe': 'اشترك',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الاستخدام',

    // Notifications
    'notifications.loading': 'جاري تحميل الإشعارات...',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.view': 'عرض',
    'notifications.viewAll': 'عرض كل الإشعارات',
    'notifications.title': 'الإشعارات',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr'); // French as default

  const t = (key: string, params?: Record<string, any>) => {
    const translation = translations[language][key] || key;

    if (params) {
      return Object.keys(params).reduce((str, param) => {
        return str.replace(new RegExp(`{${param}}`, 'g'), params[param]);
      }, translation);
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
